### ISSUE TITLE
This is for Docker, right?

### ISSUE THREAD

**Issue by phpguru** [SeerUK/OSXContainerHost#3]
I'm on a Macbook Pro trying different containers having NFS support (this, in addition to yungsang & dduportal) I've cloned this repo, CD into the directory, vagrantup, and 

1. Ansible provisioners fail
2. docker is not running, so no docker commands work
3. vagrant ssh && docker ___ results in  docker is not installed

I guess I was hoping this container was just built ready to start importing containers but am I missing something? Do I need to install Ansible on the Mac to provision docker inside the container?

**Comment by SeerUK** [comment]
Perhaps I need to make the prerequisites section a bit clearer, those are prerequisites on the host. You must have Ansible installed on the host.

Also, with any luck you shouldn't need to ssh into the VM. Make sure you read the rest of the readme ;)

**Comment by phpguru** [comment]
Makes sense now. I assumed that Docker was installed in trusty; guessing you use Ansible for that, which I've not installed. Thanks for the reply!

**Comment by phpguru** [comment]
Okay, still confused I guess. I installed Ansible (under Mavericks) with `sudo pip install ansible --quiet`. I commented out the boot2docker lines I have in ~/.bash_profile and added the one for DOCKER_HOST as you have in the README.md. I ran `vagrant up` and `vagrant provision` and it all seemed to work. When I run `docker ps -a` I get: `FATA[0000] Couldn't read ca cert /Users/me/.docker/ca.pem: open /Users/me/.docker/ca.pem: no such file or directory` - do you know how to fix that?

Interestingly, I tried `vagrant ssh` and running `docker ps -a` inside the Trusty box, and it asks, `Are you sure docker is running?` So I `ps aux | grep docker` and it has `    root      6281  0.1  0.2 127492 10432 ?        Sl   16:06   0:01 /usr/bin/docker -d -H 0.0.0.0:2375` therefore I am at a loss.

**Comment by SeerUK** [comment]
The service in the VM is called `dockerd` (IIRC, it's been a while since I've touched this...). I'm not sure about the certificate issue, but that seems to be an issue on your MacBook :S
