### ISSUE TITLE
Support for Docker 1.5 TLS, and compatibility with boot2docker.

### ISSUE THREAD

**Issue by digitalkaoz** [SeerUK/OSXContainerHost#5]
at first: THANKS dude! now i have reasonable fast docker applications.

a few improvements could still be done:

* install docker inside the image (with their repo)
* copy over the boot2docker certificates (since 1.4? 1.5 they require TLS...)
* change the ip to the boot2docker one
* create a startscript which uses these certs

im not familar with ansible but did all the steps by hand, so i can assist on that. maybe its not possible to automate everything.

**Comment by SeerUK** [comment]
Those improvements would certainly be great indeed. I am working on a custom Vagrant box, hopefully I'll be able to cut out the Ansible dependency.

Does boot2docker have a static IP set for it? What I was thinking of doing was forwarding the Docker daemon port to 2375 on the host, so it could be accessed via `tcp://localhost:2375` instead.

I'll have to look into the TLS stuff more, I was not aware of this! Cheers for the heads up. I'll get back to you when I've made some progress :)

**Comment by digitalkaoz** [comment]
yeah i think the boot2docker is always the same...but you can find it out on the host machine with`boot2docker ip`

without tls its very hard to get working nd is not recommend
